version: 0.2

env:
  shell: bash
  variables:
    SOLUTION: .\yeen.land.sln
    PACKAGE_DIRECTORY: .\packages

phases:
  install:
    commands:
      - echo Installing dependencies...
      - /usr/local/bin/dotnet-install.sh --channel 6.0
      - dotnet tool restore
    finally:
      - echo Install phase complete
  build:
    commands:
      - echo Running build tasks...
      - pushd src/yeen.land-api/
      - dotnet lambda deploy-function
      - popd
      - pushd src/yeen.land-homepage/
      - dotnet lambda deploy-function
      - popd
      - pushd src/yeen.land-on-s3-push/
      - dotnet lambda deploy-function
      - pushd src/yeen.land-permalink/
      - dotnet lambda deploy-function
    finally:
      - echo Build phase complete
      
artifacts:
  files:
    - ./src/yeen.land-api/bin/Release/net6.0/yeen.land-api.zip
    - ./src/yeen.land-homepage/bin/Release/net6.0/yeen.land-homepage.zip
    - ./src/yeen.land-on-s3-push/bin/Release/net6.0/yeen.land-on-s3-push.zip
    - ./src/yeen.land-permalink/bin/Release/net6.0/yeen.land-permalink.zip
