version: 0.2

env:
  shell: bash
  variables:
    DOTNET_NOLOGO: 1

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel 6.0
      - dotnet tool restore
  build:
    commands:
      - pushd src/yeen.land-api/ && dotnet lambda deploy-function && popd
      - pushd src/yeen.land-homepage/ && dotnet lambda deploy-function && popd
      - pushd src/yeen.land-on-s3-push/ && dotnet lambda deploy-function && popd
      - pushd src/yeen.land-permalink/ && dotnet lambda deploy-function && popd
      
artifacts:
  files:
    - ./src/yeen.land-api/bin/Release/net6.0/yeen.land-api.zip
    - ./src/yeen.land-homepage/bin/Release/net6.0/yeen.land-homepage.zip
    - ./src/yeen.land-on-s3-push/bin/Release/net6.0/yeen.land-on-s3-push.zip
    - ./src/yeen.land-permalink/bin/Release/net6.0/yeen.land-permalink.zip
